### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by jonaharagon** [ModernTLD/Cesium#20]
We should add email notifications (via SMTP).

- [ ] SMTP Connection
- [ ] Account Activation Emails
- [ ] "Domain Deleted" Notifications (after #12)
- [ ] Expiry Notifications (after #13)
- [ ] Mass Notifications (allow admins to send arbitrary notices, in #17)

We are collecting emails after change #9.
